### ISSUE TITLE
Active Stream isn't working 

### ISSUE THREAD

**Issue by madpenny** [pwrstudio/eyebeam-frontend#4] opened 2021-02-08 17:32 UTC
<img width="465" alt="Screen Shot 2021-02-08 at 12 09 15 PM" src="https://user-images.githubusercontent.com/31375201/107258392-b9d62080-6a09-11eb-8d07-883c2ab4c023.png">
<img width="719" alt="Screen Shot 2021-02-08 at 12 31 25 PM" src="https://user-images.githubusercontent.com/31375201/107258393-ba6eb700-6a09-11eb-9993-9dd07fbad01a.png">

**Comment by pwrstudio** [comment] 2021-02-10 10:13
Caused by update to the sanity CMS. Should be fixed by this commit:
https://github.com/pwrstudio/eyebeam-frontend/commit/5ad57bb7b0173dab470066589170d012faa9f070

**Closed as completed by pwrstudio** 2021-02-10 10:13 UTC
